apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
spec:
  encryptedData:
    token: AgAHDqLT8iTASeFOY8zlDMfp0uibZson4vPUT/vSSdR1qahAWFD9Q7wyIRXGsPKOfTgDZmbkVkgEGs2xVpQVpfNCamV+XsJUIyYNR1nWES+Rd3WrAXeEfctCKFpmgP/OGIAkgevoXxOR5m7JdJ3NWQH9EYseTtTy7fjD4uHS8BW3+24V8B8z8iqTFhuCdO1sKCZBcmqW4zRS57nAYzlPJpiHDBCgVEvtbEKWwxcYbtKAsvn1q+gTZqJ8n7QF3Vn+ed3us7pzOCBNZSiB7xiZmcPXAvuV61pzRjlsS+J4pWPkdA3Sk3pXfG9nRN5gABtQt7kFpyNsfOF0isYigEjRvtFF/R+TGIVu7sZwUlhQdqG9rIpCtMhQ86JQ3idTT2rrDjR2IU2+RdZZFf7UOGF1WJXNksupoEtgAKa6J38bM7+qLHR26dvjH4UVw81GowMkSuPJc6miFbaAJM1RLGYu0+3EC2Z/qmo15wdPJkF63JP9Cbjbat46thKWI2nDN+GuNC5mnicLn2x957WtbF7kRw7y8un/YXcc01oJhBlDw1AgWcAj2jb6xUygXs/k0zlmQAhaEPCH5P7lkO3V6txupfxSePPi1GAJMpQjRTztwStEgnAQejl8mZDxAkW+fvcFiARktIjvCEOpbi0SEIFKe9IEr7dsUAJDC86ypQGXqSM83vdyrvUQkO5OiGaHJwbeZ5Mb5jQCmb5l8ACZVdGIi8+vHLWJfDyI/djxNISF3RF4TXcpl+qkAbiC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
    type: Opaque
