---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      repositories:
        - owner: angelokurtis
          names:
            - k8s-automation
      # Github will send events to following port and endpoint
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://eventsource-8ac5e13d.nip.io
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: false
      active: true
      contentType: json