apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default.event-bus.yaml
  - github-access.sealed-secret.yaml
  - github-eventsource.ingress.yaml
  - github.event-source.yaml
  - github.sensor.yaml
  - operate-workflow-role-binding.role-binding.yaml
  - operate-workflow-role.role.yaml
  - operate-workflow-sa.service-account.yaml
